
namespace Fordító
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.InformacioGomb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.FelismertNyelvLabel = new System.Windows.Forms.Label();
            this.LeforditottSzoveg = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NyelvValaszto = new System.Windows.Forms.ComboBox();
            this.Fordítás_Gomb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ForditandoTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NyelvFelismereseGomb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.label1 = new System.Windows.Forms.Label();
            this.Bezaras_Gomb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TalcaraHelyezes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Icon = new System.Windows.Forms.NotifyIcon(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.InformacioGomb);
            this.bunifuGradientPanel1.Controls.Add(this.FelismertNyelvLabel);
            this.bunifuGradientPanel1.Controls.Add(this.LeforditottSzoveg);
            this.bunifuGradientPanel1.Controls.Add(this.NyelvValaszto);
            this.bunifuGradientPanel1.Controls.Add(this.Fordítás_Gomb);
            this.bunifuGradientPanel1.Controls.Add(this.AC);
            this.bunifuGradientPanel1.Controls.Add(this.ForditandoTextBox);
            this.bunifuGradientPanel1.Controls.Add(this.NyelvFelismereseGomb);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.Blue;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.SlateGray;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(60)))), ((int)(((byte)(212)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 22);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(344, 329);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // InformacioGomb
            // 
            this.InformacioGomb.AllowAnimations = true;
            this.InformacioGomb.AllowMouseEffects = true;
            this.InformacioGomb.AllowToggling = false;
            this.InformacioGomb.AnimationSpeed = 200;
            this.InformacioGomb.AutoGenerateColors = false;
            this.InformacioGomb.AutoRoundBorders = false;
            this.InformacioGomb.AutoSizeLeftIcon = true;
            this.InformacioGomb.AutoSizeRightIcon = true;
            this.InformacioGomb.BackColor = System.Drawing.Color.Transparent;
            this.InformacioGomb.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.InformacioGomb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("InformacioGomb.BackgroundImage")));
            this.InformacioGomb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InformacioGomb.ButtonText = "Info";
            this.InformacioGomb.ButtonTextMarginLeft = 0;
            this.InformacioGomb.ColorContrastOnClick = 45;
            this.InformacioGomb.ColorContrastOnHover = 45;
            this.InformacioGomb.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.InformacioGomb.CustomizableEdges = borderEdges7;
            this.InformacioGomb.DialogResult = System.Windows.Forms.DialogResult.None;
            this.InformacioGomb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.InformacioGomb.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.InformacioGomb.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.InformacioGomb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.InformacioGomb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.InformacioGomb.ForeColor = System.Drawing.Color.White;
            this.InformacioGomb.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.InformacioGomb.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.InformacioGomb.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.InformacioGomb.IconMarginLeft = 11;
            this.InformacioGomb.IconPadding = 10;
            this.InformacioGomb.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.InformacioGomb.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.InformacioGomb.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.InformacioGomb.IconSize = 25;
            this.InformacioGomb.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.InformacioGomb.IdleBorderRadius = 10;
            this.InformacioGomb.IdleBorderThickness = 1;
            this.InformacioGomb.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.InformacioGomb.IdleIconLeftImage = null;
            this.InformacioGomb.IdleIconRightImage = null;
            this.InformacioGomb.IndicateFocus = false;
            this.InformacioGomb.Location = new System.Drawing.Point(287, 308);
            this.InformacioGomb.Name = "InformacioGomb";
            this.InformacioGomb.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.InformacioGomb.OnDisabledState.BorderRadius = 10;
            this.InformacioGomb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InformacioGomb.OnDisabledState.BorderThickness = 1;
            this.InformacioGomb.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.InformacioGomb.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.InformacioGomb.OnDisabledState.IconLeftImage = null;
            this.InformacioGomb.OnDisabledState.IconRightImage = null;
            this.InformacioGomb.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.InformacioGomb.onHoverState.BorderRadius = 10;
            this.InformacioGomb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InformacioGomb.onHoverState.BorderThickness = 1;
            this.InformacioGomb.onHoverState.FillColor = System.Drawing.Color.Chartreuse;
            this.InformacioGomb.onHoverState.ForeColor = System.Drawing.Color.White;
            this.InformacioGomb.onHoverState.IconLeftImage = null;
            this.InformacioGomb.onHoverState.IconRightImage = null;
            this.InformacioGomb.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.InformacioGomb.OnIdleState.BorderRadius = 10;
            this.InformacioGomb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InformacioGomb.OnIdleState.BorderThickness = 1;
            this.InformacioGomb.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.InformacioGomb.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.InformacioGomb.OnIdleState.IconLeftImage = null;
            this.InformacioGomb.OnIdleState.IconRightImage = null;
            this.InformacioGomb.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.InformacioGomb.OnPressedState.BorderRadius = 10;
            this.InformacioGomb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InformacioGomb.OnPressedState.BorderThickness = 1;
            this.InformacioGomb.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.InformacioGomb.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.InformacioGomb.OnPressedState.IconLeftImage = null;
            this.InformacioGomb.OnPressedState.IconRightImage = null;
            this.InformacioGomb.Size = new System.Drawing.Size(57, 21);
            this.InformacioGomb.TabIndex = 8;
            this.InformacioGomb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.InformacioGomb.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.InformacioGomb.TextMarginLeft = 0;
            this.InformacioGomb.TextPadding = new System.Windows.Forms.Padding(0);
            this.InformacioGomb.UseDefaultRadiusAndThickness = true;
            this.InformacioGomb.Click += new System.EventHandler(this.InformacioGomb_Click);
            // 
            // FelismertNyelvLabel
            // 
            this.FelismertNyelvLabel.AutoSize = true;
            this.FelismertNyelvLabel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.FelismertNyelvLabel.Font = new System.Drawing.Font("Ink Free", 12F, System.Drawing.FontStyle.Bold);
            this.FelismertNyelvLabel.Location = new System.Drawing.Point(0, 309);
            this.FelismertNyelvLabel.Name = "FelismertNyelvLabel";
            this.FelismertNyelvLabel.Size = new System.Drawing.Size(51, 20);
            this.FelismertNyelvLabel.TabIndex = 7;
            this.FelismertNyelvLabel.Text = "Nyelv";
            // 
            // LeforditottSzoveg
            // 
            this.LeforditottSzoveg.AcceptsReturn = false;
            this.LeforditottSzoveg.AcceptsTab = false;
            this.LeforditottSzoveg.AnimationSpeed = 200;
            this.LeforditottSzoveg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.LeforditottSzoveg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.LeforditottSzoveg.AutoSizeHeight = true;
            this.LeforditottSzoveg.BackColor = System.Drawing.Color.White;
            this.LeforditottSzoveg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LeforditottSzoveg.BackgroundImage")));
            this.LeforditottSzoveg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.LeforditottSzoveg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LeforditottSzoveg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LeforditottSzoveg.BorderColorIdle = System.Drawing.Color.Silver;
            this.LeforditottSzoveg.BorderRadius = 1;
            this.LeforditottSzoveg.BorderThickness = 1;
            this.LeforditottSzoveg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.LeforditottSzoveg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.LeforditottSzoveg.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.LeforditottSzoveg.DefaultText = "";
            this.LeforditottSzoveg.FillColor = System.Drawing.Color.White;
            this.LeforditottSzoveg.HideSelection = true;
            this.LeforditottSzoveg.IconLeft = null;
            this.LeforditottSzoveg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.LeforditottSzoveg.IconPadding = 10;
            this.LeforditottSzoveg.IconRight = null;
            this.LeforditottSzoveg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.LeforditottSzoveg.Lines = new string[0];
            this.LeforditottSzoveg.Location = new System.Drawing.Point(9, 222);
            this.LeforditottSzoveg.MaxLength = 32767;
            this.LeforditottSzoveg.MinimumSize = new System.Drawing.Size(1, 1);
            this.LeforditottSzoveg.Modified = false;
            this.LeforditottSzoveg.Multiline = true;
            this.LeforditottSzoveg.Name = "LeforditottSzoveg";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LeforditottSzoveg.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.LeforditottSzoveg.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LeforditottSzoveg.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LeforditottSzoveg.OnIdleState = stateProperties4;
            this.LeforditottSzoveg.Padding = new System.Windows.Forms.Padding(3);
            this.LeforditottSzoveg.PasswordChar = '\0';
            this.LeforditottSzoveg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.LeforditottSzoveg.PlaceholderText = "Lefordított Szöveg";
            this.LeforditottSzoveg.ReadOnly = false;
            this.LeforditottSzoveg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.LeforditottSzoveg.SelectedText = "";
            this.LeforditottSzoveg.SelectionLength = 0;
            this.LeforditottSzoveg.SelectionStart = 0;
            this.LeforditottSzoveg.ShortcutsEnabled = true;
            this.LeforditottSzoveg.Size = new System.Drawing.Size(327, 84);
            this.LeforditottSzoveg.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.LeforditottSzoveg.TabIndex = 6;
            this.LeforditottSzoveg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.LeforditottSzoveg.TextMarginBottom = 0;
            this.LeforditottSzoveg.TextMarginLeft = 3;
            this.LeforditottSzoveg.TextMarginTop = 1;
            this.LeforditottSzoveg.TextPlaceholder = "Lefordított Szöveg";
            this.LeforditottSzoveg.UseSystemPasswordChar = false;
            this.LeforditottSzoveg.WordWrap = true;
            // 
            // NyelvValaszto
            // 
            this.NyelvValaszto.FormattingEnabled = true;
            this.NyelvValaszto.Location = new System.Drawing.Point(9, 195);
            this.NyelvValaszto.Name = "NyelvValaszto";
            this.NyelvValaszto.Size = new System.Drawing.Size(327, 21);
            this.NyelvValaszto.TabIndex = 5;
            // 
            // Fordítás_Gomb
            // 
            this.Fordítás_Gomb.AllowAnimations = true;
            this.Fordítás_Gomb.AllowMouseEffects = true;
            this.Fordítás_Gomb.AllowToggling = false;
            this.Fordítás_Gomb.AnimationSpeed = 200;
            this.Fordítás_Gomb.AutoGenerateColors = false;
            this.Fordítás_Gomb.AutoRoundBorders = false;
            this.Fordítás_Gomb.AutoSizeLeftIcon = true;
            this.Fordítás_Gomb.AutoSizeRightIcon = true;
            this.Fordítás_Gomb.BackColor = System.Drawing.Color.Transparent;
            this.Fordítás_Gomb.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Fordítás_Gomb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Fordítás_Gomb.BackgroundImage")));
            this.Fordítás_Gomb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Fordítás_Gomb.ButtonText = "Fordítás";
            this.Fordítás_Gomb.ButtonTextMarginLeft = 0;
            this.Fordítás_Gomb.ColorContrastOnClick = 45;
            this.Fordítás_Gomb.ColorContrastOnHover = 45;
            this.Fordítás_Gomb.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Fordítás_Gomb.CustomizableEdges = borderEdges1;
            this.Fordítás_Gomb.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Fordítás_Gomb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Fordítás_Gomb.DisabledFillColor = System.Drawing.Color.Empty;
            this.Fordítás_Gomb.DisabledForecolor = System.Drawing.Color.Empty;
            this.Fordítás_Gomb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Fordítás_Gomb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Fordítás_Gomb.ForeColor = System.Drawing.Color.White;
            this.Fordítás_Gomb.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Fordítás_Gomb.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Fordítás_Gomb.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Fordítás_Gomb.IconMarginLeft = 11;
            this.Fordítás_Gomb.IconPadding = 10;
            this.Fordítás_Gomb.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Fordítás_Gomb.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Fordítás_Gomb.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Fordítás_Gomb.IconSize = 25;
            this.Fordítás_Gomb.IdleBorderColor = System.Drawing.Color.Empty;
            this.Fordítás_Gomb.IdleBorderRadius = 0;
            this.Fordítás_Gomb.IdleBorderThickness = 0;
            this.Fordítás_Gomb.IdleFillColor = System.Drawing.Color.Empty;
            this.Fordítás_Gomb.IdleIconLeftImage = null;
            this.Fordítás_Gomb.IdleIconRightImage = null;
            this.Fordítás_Gomb.IndicateFocus = false;
            this.Fordítás_Gomb.Location = new System.Drawing.Point(174, 155);
            this.Fordítás_Gomb.Name = "Fordítás_Gomb";
            this.Fordítás_Gomb.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Fordítás_Gomb.OnDisabledState.BorderRadius = 1;
            this.Fordítás_Gomb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Fordítás_Gomb.OnDisabledState.BorderThickness = 1;
            this.Fordítás_Gomb.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Fordítás_Gomb.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Fordítás_Gomb.OnDisabledState.IconLeftImage = null;
            this.Fordítás_Gomb.OnDisabledState.IconRightImage = null;
            this.Fordítás_Gomb.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.Fordítás_Gomb.onHoverState.BorderRadius = 1;
            this.Fordítás_Gomb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Fordítás_Gomb.onHoverState.BorderThickness = 1;
            this.Fordítás_Gomb.onHoverState.FillColor = System.Drawing.Color.Lime;
            this.Fordítás_Gomb.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Fordítás_Gomb.onHoverState.IconLeftImage = null;
            this.Fordítás_Gomb.onHoverState.IconRightImage = null;
            this.Fordítás_Gomb.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Fordítás_Gomb.OnIdleState.BorderRadius = 1;
            this.Fordítás_Gomb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Fordítás_Gomb.OnIdleState.BorderThickness = 1;
            this.Fordítás_Gomb.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Fordítás_Gomb.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Fordítás_Gomb.OnIdleState.IconLeftImage = null;
            this.Fordítás_Gomb.OnIdleState.IconRightImage = null;
            this.Fordítás_Gomb.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Fordítás_Gomb.OnPressedState.BorderRadius = 1;
            this.Fordítás_Gomb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Fordítás_Gomb.OnPressedState.BorderThickness = 1;
            this.Fordítás_Gomb.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Fordítás_Gomb.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Fordítás_Gomb.OnPressedState.IconLeftImage = null;
            this.Fordítás_Gomb.OnPressedState.IconRightImage = null;
            this.Fordítás_Gomb.Size = new System.Drawing.Size(162, 33);
            this.Fordítás_Gomb.TabIndex = 4;
            this.Fordítás_Gomb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Fordítás_Gomb.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Fordítás_Gomb.TextMarginLeft = 0;
            this.Fordítás_Gomb.TextPadding = new System.Windows.Forms.Padding(0);
            this.Fordítás_Gomb.UseDefaultRadiusAndThickness = true;
            this.Fordítás_Gomb.Click += new System.EventHandler(this.Fordítás_Gomb_Click);
            // 
            // AC
            // 
            this.AC.AllowAnimations = true;
            this.AC.AllowMouseEffects = true;
            this.AC.AllowToggling = false;
            this.AC.AnimationSpeed = 200;
            this.AC.AutoGenerateColors = false;
            this.AC.AutoRoundBorders = false;
            this.AC.AutoSizeLeftIcon = true;
            this.AC.AutoSizeRightIcon = true;
            this.AC.BackColor = System.Drawing.Color.Transparent;
            this.AC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.AC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AC.BackgroundImage")));
            this.AC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AC.ButtonText = "Lehetseges nyelvek feltöltése";
            this.AC.ButtonTextMarginLeft = 0;
            this.AC.ColorContrastOnClick = 45;
            this.AC.ColorContrastOnHover = 45;
            this.AC.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AC.CustomizableEdges = borderEdges2;
            this.AC.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AC.DisabledFillColor = System.Drawing.Color.Empty;
            this.AC.DisabledForecolor = System.Drawing.Color.Empty;
            this.AC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AC.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AC.ForeColor = System.Drawing.Color.White;
            this.AC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AC.IconMarginLeft = 11;
            this.AC.IconPadding = 10;
            this.AC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AC.IconSize = 25;
            this.AC.IdleBorderColor = System.Drawing.Color.Empty;
            this.AC.IdleBorderRadius = 0;
            this.AC.IdleBorderThickness = 0;
            this.AC.IdleFillColor = System.Drawing.Color.Empty;
            this.AC.IdleIconLeftImage = null;
            this.AC.IdleIconRightImage = null;
            this.AC.IndicateFocus = false;
            this.AC.Location = new System.Drawing.Point(9, 155);
            this.AC.Name = "AC";
            this.AC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AC.OnDisabledState.BorderRadius = 1;
            this.AC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AC.OnDisabledState.BorderThickness = 1;
            this.AC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AC.OnDisabledState.IconLeftImage = null;
            this.AC.OnDisabledState.IconRightImage = null;
            this.AC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.AC.onHoverState.BorderRadius = 1;
            this.AC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AC.onHoverState.BorderThickness = 1;
            this.AC.onHoverState.FillColor = System.Drawing.Color.Lime;
            this.AC.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AC.onHoverState.IconLeftImage = null;
            this.AC.onHoverState.IconRightImage = null;
            this.AC.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AC.OnIdleState.BorderRadius = 1;
            this.AC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AC.OnIdleState.BorderThickness = 1;
            this.AC.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AC.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AC.OnIdleState.IconLeftImage = null;
            this.AC.OnIdleState.IconRightImage = null;
            this.AC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AC.OnPressedState.BorderRadius = 1;
            this.AC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AC.OnPressedState.BorderThickness = 1;
            this.AC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AC.OnPressedState.IconLeftImage = null;
            this.AC.OnPressedState.IconRightImage = null;
            this.AC.Size = new System.Drawing.Size(162, 33);
            this.AC.TabIndex = 3;
            this.AC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AC.TextMarginLeft = 0;
            this.AC.TextPadding = new System.Windows.Forms.Padding(0);
            this.AC.UseDefaultRadiusAndThickness = true;
            this.AC.Click += new System.EventHandler(this.AC_Click);
            // 
            // ForditandoTextBox
            // 
            this.ForditandoTextBox.AcceptsReturn = false;
            this.ForditandoTextBox.AcceptsTab = false;
            this.ForditandoTextBox.AnimationSpeed = 200;
            this.ForditandoTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ForditandoTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ForditandoTextBox.AutoSizeHeight = true;
            this.ForditandoTextBox.BackColor = System.Drawing.Color.White;
            this.ForditandoTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ForditandoTextBox.BackgroundImage")));
            this.ForditandoTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ForditandoTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ForditandoTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ForditandoTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.ForditandoTextBox.BorderRadius = 1;
            this.ForditandoTextBox.BorderThickness = 1;
            this.ForditandoTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ForditandoTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ForditandoTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ForditandoTextBox.DefaultText = "";
            this.ForditandoTextBox.FillColor = System.Drawing.Color.White;
            this.ForditandoTextBox.HideSelection = true;
            this.ForditandoTextBox.IconLeft = null;
            this.ForditandoTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ForditandoTextBox.IconPadding = 10;
            this.ForditandoTextBox.IconRight = null;
            this.ForditandoTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ForditandoTextBox.Lines = new string[0];
            this.ForditandoTextBox.Location = new System.Drawing.Point(9, 12);
            this.ForditandoTextBox.MaxLength = 32767;
            this.ForditandoTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.ForditandoTextBox.Modified = false;
            this.ForditandoTextBox.Multiline = true;
            this.ForditandoTextBox.Name = "ForditandoTextBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ForditandoTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ForditandoTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ForditandoTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ForditandoTextBox.OnIdleState = stateProperties8;
            this.ForditandoTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.ForditandoTextBox.PasswordChar = '\0';
            this.ForditandoTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ForditandoTextBox.PlaceholderText = "Add meg a fordítandó szöveget";
            this.ForditandoTextBox.ReadOnly = false;
            this.ForditandoTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ForditandoTextBox.SelectedText = "";
            this.ForditandoTextBox.SelectionLength = 0;
            this.ForditandoTextBox.SelectionStart = 0;
            this.ForditandoTextBox.ShortcutsEnabled = true;
            this.ForditandoTextBox.Size = new System.Drawing.Size(327, 77);
            this.ForditandoTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.ForditandoTextBox.TabIndex = 1;
            this.ForditandoTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ForditandoTextBox.TextMarginBottom = 0;
            this.ForditandoTextBox.TextMarginLeft = 3;
            this.ForditandoTextBox.TextMarginTop = 1;
            this.ForditandoTextBox.TextPlaceholder = "Add meg a fordítandó szöveget";
            this.ForditandoTextBox.UseSystemPasswordChar = false;
            this.ForditandoTextBox.WordWrap = true;
            // 
            // NyelvFelismereseGomb
            // 
            this.NyelvFelismereseGomb.AllowAnimations = true;
            this.NyelvFelismereseGomb.AllowMouseEffects = true;
            this.NyelvFelismereseGomb.AllowToggling = false;
            this.NyelvFelismereseGomb.AnimationSpeed = 200;
            this.NyelvFelismereseGomb.AutoGenerateColors = false;
            this.NyelvFelismereseGomb.AutoRoundBorders = false;
            this.NyelvFelismereseGomb.AutoSizeLeftIcon = true;
            this.NyelvFelismereseGomb.AutoSizeRightIcon = true;
            this.NyelvFelismereseGomb.BackColor = System.Drawing.Color.Transparent;
            this.NyelvFelismereseGomb.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.NyelvFelismereseGomb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NyelvFelismereseGomb.BackgroundImage")));
            this.NyelvFelismereseGomb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NyelvFelismereseGomb.ButtonText = "Nyelv Felismerése";
            this.NyelvFelismereseGomb.ButtonTextMarginLeft = 0;
            this.NyelvFelismereseGomb.ColorContrastOnClick = 45;
            this.NyelvFelismereseGomb.ColorContrastOnHover = 45;
            this.NyelvFelismereseGomb.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.NyelvFelismereseGomb.CustomizableEdges = borderEdges3;
            this.NyelvFelismereseGomb.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NyelvFelismereseGomb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NyelvFelismereseGomb.DisabledFillColor = System.Drawing.Color.Empty;
            this.NyelvFelismereseGomb.DisabledForecolor = System.Drawing.Color.Empty;
            this.NyelvFelismereseGomb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NyelvFelismereseGomb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.NyelvFelismereseGomb.ForeColor = System.Drawing.Color.White;
            this.NyelvFelismereseGomb.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NyelvFelismereseGomb.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NyelvFelismereseGomb.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NyelvFelismereseGomb.IconMarginLeft = 11;
            this.NyelvFelismereseGomb.IconPadding = 10;
            this.NyelvFelismereseGomb.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NyelvFelismereseGomb.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NyelvFelismereseGomb.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NyelvFelismereseGomb.IconSize = 25;
            this.NyelvFelismereseGomb.IdleBorderColor = System.Drawing.Color.Empty;
            this.NyelvFelismereseGomb.IdleBorderRadius = 0;
            this.NyelvFelismereseGomb.IdleBorderThickness = 0;
            this.NyelvFelismereseGomb.IdleFillColor = System.Drawing.Color.Empty;
            this.NyelvFelismereseGomb.IdleIconLeftImage = null;
            this.NyelvFelismereseGomb.IdleIconRightImage = null;
            this.NyelvFelismereseGomb.IndicateFocus = false;
            this.NyelvFelismereseGomb.Location = new System.Drawing.Point(9, 95);
            this.NyelvFelismereseGomb.Name = "NyelvFelismereseGomb";
            this.NyelvFelismereseGomb.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NyelvFelismereseGomb.OnDisabledState.BorderRadius = 1;
            this.NyelvFelismereseGomb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NyelvFelismereseGomb.OnDisabledState.BorderThickness = 1;
            this.NyelvFelismereseGomb.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NyelvFelismereseGomb.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NyelvFelismereseGomb.OnDisabledState.IconLeftImage = null;
            this.NyelvFelismereseGomb.OnDisabledState.IconRightImage = null;
            this.NyelvFelismereseGomb.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.NyelvFelismereseGomb.onHoverState.BorderRadius = 1;
            this.NyelvFelismereseGomb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NyelvFelismereseGomb.onHoverState.BorderThickness = 1;
            this.NyelvFelismereseGomb.onHoverState.FillColor = System.Drawing.Color.Lime;
            this.NyelvFelismereseGomb.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NyelvFelismereseGomb.onHoverState.IconLeftImage = null;
            this.NyelvFelismereseGomb.onHoverState.IconRightImage = null;
            this.NyelvFelismereseGomb.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.NyelvFelismereseGomb.OnIdleState.BorderRadius = 1;
            this.NyelvFelismereseGomb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NyelvFelismereseGomb.OnIdleState.BorderThickness = 1;
            this.NyelvFelismereseGomb.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.NyelvFelismereseGomb.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.NyelvFelismereseGomb.OnIdleState.IconLeftImage = null;
            this.NyelvFelismereseGomb.OnIdleState.IconRightImage = null;
            this.NyelvFelismereseGomb.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NyelvFelismereseGomb.OnPressedState.BorderRadius = 1;
            this.NyelvFelismereseGomb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NyelvFelismereseGomb.OnPressedState.BorderThickness = 1;
            this.NyelvFelismereseGomb.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NyelvFelismereseGomb.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NyelvFelismereseGomb.OnPressedState.IconLeftImage = null;
            this.NyelvFelismereseGomb.OnPressedState.IconRightImage = null;
            this.NyelvFelismereseGomb.Size = new System.Drawing.Size(327, 33);
            this.NyelvFelismereseGomb.TabIndex = 0;
            this.NyelvFelismereseGomb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.NyelvFelismereseGomb.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NyelvFelismereseGomb.TextMarginLeft = 0;
            this.NyelvFelismereseGomb.TextPadding = new System.Windows.Forms.Padding(0);
            this.NyelvFelismereseGomb.UseDefaultRadiusAndThickness = true;
            this.NyelvFelismereseGomb.Click += new System.EventHandler(this.NyelvFelismereseGomb_Click);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Left;
            this.label1.Font = new System.Drawing.Font("Ink Free", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(0, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(186, 20);
            this.label1.TabIndex = 1;
            this.label1.Text = "Fordító 1.0 by:Controlix";
            // 
            // Bezaras_Gomb
            // 
            this.Bezaras_Gomb.AllowAnimations = true;
            this.Bezaras_Gomb.AllowMouseEffects = true;
            this.Bezaras_Gomb.AllowToggling = false;
            this.Bezaras_Gomb.AnimationSpeed = 200;
            this.Bezaras_Gomb.AutoGenerateColors = false;
            this.Bezaras_Gomb.AutoRoundBorders = false;
            this.Bezaras_Gomb.AutoSizeLeftIcon = true;
            this.Bezaras_Gomb.AutoSizeRightIcon = true;
            this.Bezaras_Gomb.BackColor = System.Drawing.Color.Transparent;
            this.Bezaras_Gomb.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Bezaras_Gomb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Bezaras_Gomb.BackgroundImage")));
            this.Bezaras_Gomb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bezaras_Gomb.ButtonText = "X";
            this.Bezaras_Gomb.ButtonTextMarginLeft = 0;
            this.Bezaras_Gomb.ColorContrastOnClick = 45;
            this.Bezaras_Gomb.ColorContrastOnHover = 45;
            this.Bezaras_Gomb.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Bezaras_Gomb.CustomizableEdges = borderEdges5;
            this.Bezaras_Gomb.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Bezaras_Gomb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bezaras_Gomb.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bezaras_Gomb.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bezaras_Gomb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Bezaras_Gomb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Bezaras_Gomb.ForeColor = System.Drawing.Color.White;
            this.Bezaras_Gomb.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Bezaras_Gomb.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Bezaras_Gomb.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Bezaras_Gomb.IconMarginLeft = 11;
            this.Bezaras_Gomb.IconPadding = 10;
            this.Bezaras_Gomb.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Bezaras_Gomb.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Bezaras_Gomb.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Bezaras_Gomb.IconSize = 25;
            this.Bezaras_Gomb.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Bezaras_Gomb.IdleBorderRadius = 10;
            this.Bezaras_Gomb.IdleBorderThickness = 1;
            this.Bezaras_Gomb.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Bezaras_Gomb.IdleIconLeftImage = null;
            this.Bezaras_Gomb.IdleIconRightImage = null;
            this.Bezaras_Gomb.IndicateFocus = false;
            this.Bezaras_Gomb.Location = new System.Drawing.Point(323, 0);
            this.Bezaras_Gomb.Name = "Bezaras_Gomb";
            this.Bezaras_Gomb.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bezaras_Gomb.OnDisabledState.BorderRadius = 10;
            this.Bezaras_Gomb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bezaras_Gomb.OnDisabledState.BorderThickness = 1;
            this.Bezaras_Gomb.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bezaras_Gomb.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bezaras_Gomb.OnDisabledState.IconLeftImage = null;
            this.Bezaras_Gomb.OnDisabledState.IconRightImage = null;
            this.Bezaras_Gomb.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bezaras_Gomb.onHoverState.BorderRadius = 10;
            this.Bezaras_Gomb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bezaras_Gomb.onHoverState.BorderThickness = 1;
            this.Bezaras_Gomb.onHoverState.FillColor = System.Drawing.Color.Red;
            this.Bezaras_Gomb.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Bezaras_Gomb.onHoverState.IconLeftImage = null;
            this.Bezaras_Gomb.onHoverState.IconRightImage = null;
            this.Bezaras_Gomb.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Bezaras_Gomb.OnIdleState.BorderRadius = 10;
            this.Bezaras_Gomb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bezaras_Gomb.OnIdleState.BorderThickness = 1;
            this.Bezaras_Gomb.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Bezaras_Gomb.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Bezaras_Gomb.OnIdleState.IconLeftImage = null;
            this.Bezaras_Gomb.OnIdleState.IconRightImage = null;
            this.Bezaras_Gomb.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bezaras_Gomb.OnPressedState.BorderRadius = 10;
            this.Bezaras_Gomb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bezaras_Gomb.OnPressedState.BorderThickness = 1;
            this.Bezaras_Gomb.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bezaras_Gomb.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Bezaras_Gomb.OnPressedState.IconLeftImage = null;
            this.Bezaras_Gomb.OnPressedState.IconRightImage = null;
            this.Bezaras_Gomb.Size = new System.Drawing.Size(21, 21);
            this.Bezaras_Gomb.TabIndex = 7;
            this.Bezaras_Gomb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Bezaras_Gomb.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Bezaras_Gomb.TextMarginLeft = 0;
            this.Bezaras_Gomb.TextPadding = new System.Windows.Forms.Padding(0);
            this.Bezaras_Gomb.UseDefaultRadiusAndThickness = true;
            this.Bezaras_Gomb.Click += new System.EventHandler(this.Bezaras_Gomb_Click);
            // 
            // TalcaraHelyezes
            // 
            this.TalcaraHelyezes.AllowAnimations = true;
            this.TalcaraHelyezes.AllowMouseEffects = true;
            this.TalcaraHelyezes.AllowToggling = false;
            this.TalcaraHelyezes.AnimationSpeed = 200;
            this.TalcaraHelyezes.AutoGenerateColors = false;
            this.TalcaraHelyezes.AutoRoundBorders = false;
            this.TalcaraHelyezes.AutoSizeLeftIcon = true;
            this.TalcaraHelyezes.AutoSizeRightIcon = true;
            this.TalcaraHelyezes.BackColor = System.Drawing.Color.Transparent;
            this.TalcaraHelyezes.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.TalcaraHelyezes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TalcaraHelyezes.BackgroundImage")));
            this.TalcaraHelyezes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TalcaraHelyezes.ButtonText = "_";
            this.TalcaraHelyezes.ButtonTextMarginLeft = 0;
            this.TalcaraHelyezes.ColorContrastOnClick = 45;
            this.TalcaraHelyezes.ColorContrastOnHover = 45;
            this.TalcaraHelyezes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.TalcaraHelyezes.CustomizableEdges = borderEdges4;
            this.TalcaraHelyezes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TalcaraHelyezes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TalcaraHelyezes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TalcaraHelyezes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TalcaraHelyezes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TalcaraHelyezes.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TalcaraHelyezes.ForeColor = System.Drawing.Color.White;
            this.TalcaraHelyezes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TalcaraHelyezes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TalcaraHelyezes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TalcaraHelyezes.IconMarginLeft = 11;
            this.TalcaraHelyezes.IconPadding = 10;
            this.TalcaraHelyezes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TalcaraHelyezes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TalcaraHelyezes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TalcaraHelyezes.IconSize = 25;
            this.TalcaraHelyezes.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.TalcaraHelyezes.IdleBorderRadius = 10;
            this.TalcaraHelyezes.IdleBorderThickness = 1;
            this.TalcaraHelyezes.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.TalcaraHelyezes.IdleIconLeftImage = null;
            this.TalcaraHelyezes.IdleIconRightImage = null;
            this.TalcaraHelyezes.IndicateFocus = false;
            this.TalcaraHelyezes.Location = new System.Drawing.Point(301, 0);
            this.TalcaraHelyezes.Name = "TalcaraHelyezes";
            this.TalcaraHelyezes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TalcaraHelyezes.OnDisabledState.BorderRadius = 10;
            this.TalcaraHelyezes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TalcaraHelyezes.OnDisabledState.BorderThickness = 1;
            this.TalcaraHelyezes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TalcaraHelyezes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TalcaraHelyezes.OnDisabledState.IconLeftImage = null;
            this.TalcaraHelyezes.OnDisabledState.IconRightImage = null;
            this.TalcaraHelyezes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TalcaraHelyezes.onHoverState.BorderRadius = 10;
            this.TalcaraHelyezes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TalcaraHelyezes.onHoverState.BorderThickness = 1;
            this.TalcaraHelyezes.onHoverState.FillColor = System.Drawing.Color.SteelBlue;
            this.TalcaraHelyezes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TalcaraHelyezes.onHoverState.IconLeftImage = null;
            this.TalcaraHelyezes.onHoverState.IconRightImage = null;
            this.TalcaraHelyezes.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.TalcaraHelyezes.OnIdleState.BorderRadius = 10;
            this.TalcaraHelyezes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TalcaraHelyezes.OnIdleState.BorderThickness = 1;
            this.TalcaraHelyezes.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.TalcaraHelyezes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TalcaraHelyezes.OnIdleState.IconLeftImage = null;
            this.TalcaraHelyezes.OnIdleState.IconRightImage = null;
            this.TalcaraHelyezes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TalcaraHelyezes.OnPressedState.BorderRadius = 10;
            this.TalcaraHelyezes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TalcaraHelyezes.OnPressedState.BorderThickness = 1;
            this.TalcaraHelyezes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TalcaraHelyezes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TalcaraHelyezes.OnPressedState.IconLeftImage = null;
            this.TalcaraHelyezes.OnPressedState.IconRightImage = null;
            this.TalcaraHelyezes.Size = new System.Drawing.Size(21, 21);
            this.TalcaraHelyezes.TabIndex = 8;
            this.TalcaraHelyezes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TalcaraHelyezes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TalcaraHelyezes.TextMarginLeft = 0;
            this.TalcaraHelyezes.TextPadding = new System.Windows.Forms.Padding(0);
            this.TalcaraHelyezes.UseDefaultRadiusAndThickness = true;
            this.TalcaraHelyezes.Click += new System.EventHandler(this.TalcaraHelyezes_Click);
            // 
            // Icon
            // 
            this.Icon.Icon = ((System.Drawing.Icon)(resources.GetObject("Icon.Icon")));
            this.Icon.Text = "Fordító";
            this.Icon.Visible = true;
            this.Icon.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.Ujranagyitas);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.ClientSize = new System.Drawing.Size(344, 352);
            this.Controls.Add(this.TalcaraHelyezes);
            this.Controls.Add(this.Bezaras_Gomb);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox NyelvValaszto;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Fordítás_Gomb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AC;
        private Bunifu.UI.WinForms.BunifuTextBox ForditandoTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NyelvFelismereseGomb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Bezaras_Gomb;
        private Bunifu.UI.WinForms.BunifuTextBox LeforditottSzoveg;
        private System.Windows.Forms.Label FelismertNyelvLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton InformacioGomb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TalcaraHelyezes;
        private System.Windows.Forms.NotifyIcon Icon;
    }
}

